version: "3.9"
services:
    backend-nginx:
        build:
            context: infrastructure/backend/development/docker/nginx-debian-bullseye
        ports:
            - "80:80"
        volumes:
            - ./:/starter
        depends_on:
            - backend-php-fpm

    backend-php-fpm:
        build:
            context: infrastructure/backend/development/docker/php-fpm-debian-bullseye
        environment:
            MAILER_HOST: backend-mailer
            MAILER_PORT: 1025
            MAILER_USERNAME: alex
            MAILER_PASSWORD: 123
            MAILER_ENCRYPTION: tcp
            MAILER_FROM_EMAIL: mail@app.test
            MAILER_FROM_NAME: test
            DB: mysql
            MYSQL_HOST: backend-mysql
            MYSQL_USER: starter
            MYSQL_PASSWORD: starter
            MYSQL_DATABASE: starter
            MYSQL_CHARSET: utf8
            POSTGRES_HOST: backend-postgres
            POSTGRES_USER: starter
            POSTGRES_PASSWORD: starter
            POSTGRES_DB: starter
            POSTGRES_CHARSET: utf-8
            APPLICATION_ENV: dev
            APPLICATION_DEBUG: 1
        volumes:
            - ./:/starter

    backend-php-cli:
        build:
            context: infrastructure/backend/development/docker/php-cli-debian-bullseye
        environment:
            MAILER_HOST: backend-mailer
            MAILER_PORT: 1025
            MAILER_USERNAME: alex
            MAILER_PASSWORD: 123
            MAILER_ENCRYPTION: tcp
            MAILER_FROM_EMAIL: mail@app.test
            MAILER_FROM_NAME: test
            DB: mysql
            MYSQL_HOST: backend-mysql
            MYSQL_USER: starter
            MYSQL_PASSWORD: starter
            MYSQL_DATABASE: starter
            MYSQL_CHARSET: utf8
            POSTGRES_HOST: backend-postgres
            POSTGRES_USER: starter
            POSTGRES_PASSWORD: starter
            POSTGRES_DB: starter
            POSTGRES_CHARSET: utf-8
            APPLICATION_ENV: dev
            APPLICATION_DEBUG: 1
        volumes:
            - ./:/starter

    backend-mysql:
        image: mysql:8.0
        environment:
            MYSQL_USER: starter
            MYSQL_PASSWORD: starter
            MYSQL_ROOT_PASSWORD: starter
            MYSQL_DATABASE: starter
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        profiles:
            - db
            - mysql

    backend-postgres:
        image: postgres:14
        environment:
            POSTGRES_USER: starter
            POSTGRES_PASSWORD: starter
            POSTGRES_DB: starter
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "54321:5432"
        profiles:
            - db
            - postgres

    backend-mailer:
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"

    frontend-nodejs-cli:
        build:
            context: infrastructure/frontend/development/docker/nodejs-cli-debian-bullseye
        volumes:
            - ./:/starter
volumes:
    mysql:
    postgres:
