---
- name: debian-deploy / build
  hosts: Ddev
  roles:
      - role: debian-preconfig
        tags: debian-preconfig
      - role: debian-soft
        tags: debian-soft
- name: debian-prod / build
  hosts: Dprod
  roles:
      - role: debian-preconfig
        tags: debian-preconfig
      - role: debian-soft
        tags: debian-soft
