---
- name: php 8.1
  block:
      - name: apt signing key php 8.1
        apt_key:
            url: https://packages.sury.org/php/apt.gpg
            state: present
        tags: php-key
      - name: add apt repository php 8.1
        apt_repository:
            repo: deb https://packages.sury.org/php/ bullseye main
            update_cache: yes
        tags: php-repo
      - name: install php 8.1
        apt:
            name: "{{ packages }}"
            state: latest
        vars:
            packages:
                - php8.1-cli
                - php8.1-fpm
        tags: php-install
        debugger: on_failed
  tags: php

- name: composer
  block:
      - name: install composer
        shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/bin --filename=composer
        args:
            creates: /bin/composer
        #shell: /tmp/installer | php -- --install-dir=/bin --filename=composer --quiet
  debugger: on_failed
  tags: composer

- name: nginx
  block:
      - name: added PGP-key
        apt_key:
            url: https://nginx.org/keys/nginx_signing.key
            state: present
        tags: nginx-key
      - name: add repo nginx
        apt_repository:
            repo: deb https://nginx.org/packages/mainline/debian/ bullseye nginx
            state: present
      - name: add repo nginx src
        apt_repository:
            repo: deb-src https://nginx.org/packages/mainline/debian/ bullseye nginx
            state: present
      - name: install nginx
        apt:
            name: nginx
            update_cache: yes
            state: present
      - name: start nginx
        service:
            name: nginx
            state: started
  tags: nginx
